Do not fail on readme updates on local dev env (#47)
* Do not fail on readme updates on local dev env

* Fail locally too

* Add coloring

diff --git a/checks.bitrise.yml b/checks.bitrise.yml
--- a/checks.bitrise.yml
+++ b/checks.bitrise.yml
@@ -15,26 +15,31 @@ workflows:
             set -ex
 
             if [[ "$OSTYPE" == "linux-gnu"* ]]; then
-                # pipx is only available in OS repos from Ubuntu 23+, so we need to install via pip for now
-                ubuntu_version=$(lsb_release -rs)
-                if [[ $ubuntu_version == "20.04" ]]; then
-                    apt-get remove -y yamllint
-                    # Default Python version is the system-wide and it doesn't have venv (which is needed for pipx)
-                    apt-get update
-                    yes | apt-get install python3.8-venv
-                    # Ubuntu 20 ships with an old pip that doesn't recognize the --break-system-packages flag
-                    pip install pipx
-                else
-                    pip install --user --break-system-packages pipx
-                fi
-                export PATH="$PATH:/root/.local/bin"
-                pipx ensurepath
-                source ~/.bashrc # reload $PATH changes
+              # pipx is only available in OS repos from Ubuntu 23+, so we need to install via pip for now
+              ubuntu_version=$(lsb_release -rs)
+              if [[ $ubuntu_version == "20.04" ]]; then
+                apt-get remove -y yamllint
+                # Default Python version is the system-wide and it doesn't have venv (which is needed for pipx)
+                apt-get update
+                yes | apt-get install python3.8-venv
+                # Ubuntu 20 ships with an old pip that doesn't recognize the --break-system-packages flag
+                pip install pipx
+              else
+                pip install --user --break-system-packages pipx
+              fi
+              export PATH="$PATH:/root/.local/bin"
+              pipx ensurepath
+              source ~/.bashrc # reload $PATH changes
             else
+              if brew list pipx &>/dev/null ; then
+                echo "pipx already installed"
+              else
+                echo "Installing pipx"
                 HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1 brew install pipx
                 export PATH="$PATH:$HOME/.local/bin"
                 pipx ensurepath
                 source ~/.bashrc # reload $PATH changes
+              fi
             fi
 
             pipx install yamllint
@@ -57,18 +62,24 @@ workflows:
             #!/bin/env bash
             set -x
             if [ ! -f ./README.md ]; then
-              echo "No README.md file found, please add 'generate_readme' workflow, run it and commit the changes"
+              echo -e "\033[0;31mNo README.md file found, please add 'generate_readme' workflow, run it and commit the changes.\033[0m"
               exit 1
             fi
 
             bitrise run generate_readme
             if [ $? -ne 0 ]; then
-              echo "Failed to generate README.md, please check that 'generate_readme' workflow exists"
+              echo -e "\033[0;31mFailed to generate README.md, please check that 'generate_readme' workflow exist.\033[0m"
               exit 1
             fi
 
-            if ! diff -u README.md README.md.backup; then
-              echo "README.md is not consistent with step.yml, please run 'bitrise run generate_readme' and commit the changes"
+            diff -u README.md README.md.backup
+            if [ $? -ne 0 ]; then
+              echo -e "\033[0;35mREADME.md was not consistent with step.yml, regenerated it\035[0m"
+              if [ $CI == "true" ]; then
+                echo -e "\033[0;31mPlease run 'bitrise run generate_readme' locally and commit the changes.\033[0m"
+              else
+                echo -e "\033[0;31mPlease compare README.md and README.md.backup to see diff, and commit README.md.\033[0m"
+              fi
               exit 1
             fi
     - git::https://github.com/bitrise-steplib/steps-validate-json-schema.git@main:
